application: relationshipanalytics
version: v4
runtime: python27
api_version: 1
threadsafe: true

libraries:
- name: webapp2
  version: latest

- name: jinja2
  version: latest

handlers:
- url: /css
  static_dir: css

- url: /js
  static_dir: js

- url: /static
  static_dir: static

- url: /fonts
  static_dir: fonts

- url: /blobstore.*
  script: blobstore.app

- url: /.*
  script: relationshipanalytics.application
  secure: always
  login: required