application: relationshipanalytics
version: v7
runtime: python27
api_version: 1
threadsafe: true

libraries:
- name: pycrypto
  version: latest

- name: endpoints
  version: 1.0

- name: webapp2
  version: latest

- name: jinja2
  version: latest

handlers:
- url: /css
  static_dir: css

- url: /js
  static_dir: js

- url: /static
  static_dir: static

- url: /fonts
  static_dir: fonts

- url: /bower_components
  static_dir: bower_components
  expiration: "12h"

- url: /blobstore.*
  script: blobstore.app

- url: /_ah/spi/.*
  script: hitlist_api.APPLICATION

- url: /.*
  script: relationshipanalytics.application
  secure: always
  login: required